### ISSUE TITLE
Dead links in the README

### ISSUE THREAD

**Issue by KenjiTakahashi** [TomWright/dasel#308]
Several links in the **Features** paragraph lead to `404`s. The hosted playground link leads to nowhere.

**Comment by TomWright** [comment]
Thanks for raising this.
I must have messed things up in the v2 docs migration. I'll fix it up 👍

**Comment by TomWright** [comment]
I've fixed the docs links in the README. Which hosted playground links are you referring to?

**Comment by KenjiTakahashi** [comment]
Thanks! Looks like the "Pre-commit hooks" link still doesn't do anything.
As for the playground, I was referring to the one in "You can test out dasel commands using the [playground](https://dasel.tomwright.me/).", but it works now. Maybe the website was down at the time?

**Comment by TomWright** [comment]
> Thanks! Looks like the "Pre-commit hooks" link still doesn't do anything. As for the playground, I was referring to the one in "You can test out dasel commands using the [playground](https://dasel.tomwright.me/).", but it works now. Maybe the website was down at the time?

Pre-commit hooks link is fixed now too.

I can only assume so, although I haven't done any maintenance on it or anything. I've probably got something messed up, I was working on www.tomwright.me -> tomwright.me in the last few days. That was working but isn't now.

I'll close this issue now though since I think I've fixed all the problems.

Thanks for raising 👍
